# Project: Projeto3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o pathClasseA/ClasseA.o utils/Utils.o pathClasseB/ClasseB.o pathClasseC/ClasseC.o pathClasseD/ClasseD.o
LINKOBJ  = main.o pathClasseA/ClasseA.o utils/Utils.o pathClasseB/ClasseB.o pathClasseC/ClasseC.o pathClasseD/ClasseD.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Projeto3.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

pathClasseA/ClasseA.o: pathClasseA/ClasseA.cpp
	$(CPP) -c pathClasseA/ClasseA.cpp -o pathClasseA/ClasseA.o $(CXXFLAGS)

utils/Utils.o: utils/Utils.cpp
	$(CPP) -c utils/Utils.cpp -o utils/Utils.o $(CXXFLAGS)

pathClasseB/ClasseB.o: pathClasseB/ClasseB.cpp
	$(CPP) -c pathClasseB/ClasseB.cpp -o pathClasseB/ClasseB.o $(CXXFLAGS)

pathClasseC/ClasseC.o: pathClasseC/ClasseC.cpp
	$(CPP) -c pathClasseC/ClasseC.cpp -o pathClasseC/ClasseC.o $(CXXFLAGS)

pathClasseD/ClasseD.o: pathClasseD/ClasseD.cpp
	$(CPP) -c pathClasseD/ClasseD.cpp -o pathClasseD/ClasseD.o $(CXXFLAGS)
